name: 3D contributions
on:
  schedule:
    - cron: "30 0 * * *"      # daily
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        with:
          USERNAME: solnikhil
      - name: Commit 3D files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update 3D profile graph" || echo "No changes"
          git push
