name: Profile metrics
on:
  schedule:
    - cron: "15 */12 * * *"   # every 12 hours, offset
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # classic PAT: repo + read:org
          user: solnikhil
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_threshold: 1%
          plugin_languages_sections: most-used

          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          plugin_stargazers: yes
          filename: metrics.svg
